#!/usr/bin/env ansible-playbook

- name: Check collector container status
  hosts: bitflow-collector
  tasks:
    - include_role:
        name: ../../roles/bitflow-collector
        tasks_from: check-container-status

