#!/usr/bin/env ansible-playbook

- name: Disable file output of data collectors
  hosts: bitflow-collector
  tasks:
    - include_role:
        name: ../../roles/bitflow-collector
        tasks_from: disable-data-collection

