#!/usr/bin/env ansible-playbook

- name: Unset collector tags, stop file outputs of collectors
  hosts: bitflow-collector
  tasks:
    - include_role:
        name: ../../roles/bitflow-collector
        tasks_from: disable-data-collection
    - include_role:
        name: ../../roles/bitflow-collector
        tasks_from: reset-tags

